# Copyright (C) Markus Franz Xaver Johannes Oberhumer
# test minimal number of packages required for building UPX under Alpine Linux
#   clang: apk add clang cmake make
#   gcc:   apk add cmake g++ make

name: 'Test - Minimal Alpine build'
on: [workflow_dispatch]
env:
  CMAKE_REQUIRED_QUIET: 'OFF'
  CMAKE_VERBOSE_MAKEFILE: 'ON'
  CTEST_OUTPUT_ON_FAILURE: 'ON'
  DEBIAN_FRONTEND: noninteractive

jobs:
  job-alpine-clang: # uses cmake + make
    if: true
    strategy: { matrix: { container: ['alpine:edge','i386/alpine:edge'] } }
    name: ${{ format('clang {0}', matrix.container) }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: ${{ format('Build clang {0}', matrix.container) }}
        run: |
          apk update && apk upgrade && apk add clang cmake make
          wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-src.tar.xz
          tar -xoaf upx-*-src.tar.xz
          cd upx-*-src
          make    build/debug   CC="clang -static" CXX="clang++ -static"
          make    build/release CC="clang -static" CXX="clang++ -static"
          make -C build/debug   test
          make -C build/release test
          make -C build/release install DESTDIR="$PWD/Install"
          N=$(echo "upx-test-alpine-linux-clang-${{ matrix.container }}" | sed 's/[^0-9a-zA-Z_.-]/-/g')
          echo "artifact_name=$N" >> $GITHUB_ENV
      - name: ${{ format('Upload artifact {0}', env.artifact_name) }}
        if: ${{ !startsWith(matrix.container, 'i386/') }} # i386: missing nodejs on host
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: 'upx*/build/*/upx'

  job-alpine-gcc: # uses cmake + make
    if: true
    strategy: { matrix: { container: ['alpine:edge','i386/alpine:edge'] } }
    name: ${{ format('gcc {0}', matrix.container) }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: ${{ format('Build gcc {0}', matrix.container) }}
        run: |
          apk update && apk upgrade && apk add cmake g++ make
          wget https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-src.tar.xz
          tar -xoaf upx-*-src.tar.xz
          cd upx-*-src
          make    build/debug   CC="gcc -static" CXX="g++ -static"
          make    build/release CC="gcc -static" CXX="g++ -static"
          make -C build/debug   test
          make -C build/release test
          make -C build/release install DESTDIR="$PWD/Install"
          N=$(echo "upx-test-alpine-linux-gcc-${{ matrix.container }}" | sed 's/[^0-9a-zA-Z_.-]/-/g')
          echo "artifact_name=$N" >> $GITHUB_ENV
      - name: ${{ format('Upload artifact {0}', env.artifact_name) }}
        if: ${{ !startsWith(matrix.container, 'i386/') }} # i386: missing nodejs on host
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifact_name }}
          path: 'upx*/build/*/upx'
